/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Serial;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class Login_Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    public Login_Servidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Login_de_acesso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Senha_de_acesso = new javax.swing.JPasswordField();
        Botão_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 60, 70, 20);
        getContentPane().add(Login_de_acesso);
        Login_de_acesso.setBounds(400, 60, 150, 30);

        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 90, 70, 20);
        getContentPane().add(Senha_de_acesso);
        Senha_de_acesso.setBounds(400, 90, 150, 30);

        Botão_login.setText("Entrar");
        Botão_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_loginActionPerformed(evt);
            }
        });
        getContentPane().add(Botão_login);
        Botão_login.setBounds(490, 120, 63, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cooltext276410859045753.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 40, 320, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fd.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -30, 660, 220);

        setSize(new java.awt.Dimension(641, 222));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Botão_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_loginActionPerformed
            if (Login_de_acesso.getText().equals("user") && Senha_de_acesso.getText().equals("ifpb")){
               JOptionPane.showMessageDialog(null, "Bem vindo!");
               Sistema janela = new Sistema();
               janela.setVisible(true);
               dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Acesso negado!");
            }
    }//GEN-LAST:event_Botão_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_login;
    private javax.swing.JTextField Login_de_acesso;
    private javax.swing.JPasswordField Senha_de_acesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
